@startuml
[Бортовые системы] --> [Серверная часть] : Телеметрия (MQTT/API)
[Серверная часть] --> [Веб-клиенты] : Данные для клиентов (REST/WebSocket)
[Бортовые системы] --> [Серверная часть] : Сменные задания
[Веб-клиенты] --> [Серверная часть] : Сменные задания
[Бортовые системы] --> [Датчики, метки, бортовые контроллеры]
[Серверная часть] --> [Единая база данных]
[Единая база данных] --> [Справочники, телеметрия, рейсы, статусы]
@enduml